GET http://localhost:8080/users

###

POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Neemias",
    "password": "54321"
}


###

POST http://localhost:8080/users/signin
Content-Type: application/json

{
    "name": "Neemias",
    "password": "54321"
}
